trying to fix tests by providing test settings.xml in home folder

diff --git a/.github/workflows/maven-build-test.yml b/.github/workflows/maven-build-test.yml
--- a/.github/workflows/maven-build-test.yml
+++ b/.github/workflows/maven-build-test.yml
@@ -38,6 +38,10 @@ jobs:
         uses: actions/checkout@v3
         with:
           path: ${{ env.REPOSITORY_PATH }}
+      
+      - name: Overwrite maven settings
+        shell: bash
+        run: cp -rf ${{ env.REPOSITORY_PATH }}/.mvn/ci-settings.xml ~/.m2/settings.xml
 
       - name: Checkout & Prepare
         uses: devonfw-actions/java-maven-setup@main
@@ -50,8 +54,8 @@ jobs:
         shell: bash
         run: |
           cd ${{ env.REPOSITORY_PATH }}
-          mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve -Dmaven.repo.local=${{ github.workspace }}/.m2/repository -pl !com.devonfw.cobigen:com.devonfw.cobigen.eclipse.test -DexcludeGroupIds=com.devonfw.cobigen -T1C -Pp2-build ${{ env.MVN_BATCH_MODE }} ${{ env.MVN_HTTP_OPTIMIZATION }} || true # never fail
-          mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve-plugins -Dmaven.repo.local=${{ github.workspace }}/.m2/repository -pl !com.devonfw.cobigen:com.devonfw.cobigen.eclipse.test -DexcludeGroupIds=com.devonfw.cobigen -T1C -Pp2-build ${{ env.MVN_BATCH_MODE }} ${{ env.MVN_HTTP_OPTIMIZATION }} || true # never fail
+          mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve -pl !com.devonfw.cobigen:com.devonfw.cobigen.eclipse.test -DexcludeGroupIds=com.devonfw.cobigen -T1C -Pp2-build ${{ env.MVN_BATCH_MODE }} ${{ env.MVN_HTTP_OPTIMIZATION }} || true # never fail
+          mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve-plugins -pl !com.devonfw.cobigen:com.devonfw.cobigen.eclipse.test -DexcludeGroupIds=com.devonfw.cobigen -T1C -Pp2-build ${{ env.MVN_BATCH_MODE }} ${{ env.MVN_HTTP_OPTIMIZATION }} || true # never fail
 
   build:
     needs: cache-dependencies
@@ -108,6 +112,11 @@ jobs:
         uses: actions/checkout@v3
         with:
           path: ${{ env.REPOSITORY_PATH }}
+      
+      # need to overwrite global settings file to cath all mvn executions properly in tests
+      - name: Overwrite maven settings
+        shell: bash
+        run: cp -rf ${{ env.REPOSITORY_PATH }}/.mvn/ci-settings.xml ~/.m2/settings.xml
 
       - uses: devonfw-actions/java-maven-setup@main
         with:
