fixing odd cache path

diff --git a/.github/workflows/maven-build-test.yml b/.github/workflows/maven-build-test.yml
--- a/.github/workflows/maven-build-test.yml
+++ b/.github/workflows/maven-build-test.yml
@@ -39,13 +39,13 @@ jobs:
       - name: Checkout & Prepare
         uses: devonfw-actions/java-maven-setup@main
         with:
-          maven-cache-path: ../../.m2/repository
+          maven-cache-path: ${{ github.workspace }}/../../.m2/repository
           maven-cache-key: cobigen-dep-${{ hashFiles('**/pom.xml') }}
           clone: false # checkout in a separate / earlier step to allow eager evaluation of parameter expression like workspace or hashFiles
       
       - name: Resolve non-cobigen dependencies
         shell: bash
-        run: mvn -Dmaven.repo.local=../../.m2/repository -pl !com.devonfw.cobigen:com.devonfw.cobigen.eclipse.test org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve-plugins -DexcludeGroupIds=com.devonfw.cobigen -T1C -Pp2-build ${{ env.MVN_BATCH_MODE }} ${{ env.MVN_HTTP_OPTIMIZATION }} || true # never fail
+        run: mvn -Dmaven.repo.local=${{ github.workspace }}/../../.m2/repository -pl !com.devonfw.cobigen:com.devonfw.cobigen.eclipse.test org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve-plugins -DexcludeGroupIds=com.devonfw.cobigen -T1C -Pp2-build ${{ env.MVN_BATCH_MODE }} ${{ env.MVN_HTTP_OPTIMIZATION }} || true # never fail
 
   build:
     needs: cache-dependencies
@@ -67,7 +67,7 @@ jobs:
       - name: Checkout & Prepare
         uses: devonfw-actions/java-maven-setup@main
         with:
-          maven-cache-path: ../../.m2/repository
+          maven-cache-path: ${{ github.workspace }}/../../.m2/repository
           maven-cache-key: maven-${{ github.sha }}-${{ matrix.os }}-${{ github.run_number }} # new key will cache
           maven-cache-restore-key: cobigen-dep-${{ hashFiles('**/pom.xml') }}
           java-version: ${{ matrix.javaVersion }}
@@ -116,7 +116,7 @@ jobs:
 
       - uses: devonfw-actions/java-maven-setup@main
         with:
-          maven-cache-path: ../../.m2/repository
+          maven-cache-path: ${{ github.workspace }}/../../.m2/repository
           maven-cache-key: maven-${{ github.sha }}-${{ matrix.os }}-${{ github.run_number }} # match, restore only
           java-version: ${{ matrix.javaVersion }}
           jacoco-cache-key: jacoco-${{ github.sha }}-${{ matrix.component }} # new key will cache
@@ -168,7 +168,7 @@ jobs:
 
       - uses: devonfw-actions/java-maven-setup@main
         with:
-          maven-cache-path: ../../.m2/repository
+          maven-cache-path: ${{ github.workspace }}/../../.m2/repository
           maven-cache-key: cobigen-dep-${{ hashFiles('**/pom.xml') }}
           GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
           GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
