more cache debugging

diff --git a/.github/workflows/maven-build-test.yml b/.github/workflows/maven-build-test.yml
--- a/.github/workflows/maven-build-test.yml
+++ b/.github/workflows/maven-build-test.yml
@@ -23,7 +23,6 @@ env:
   MVN_BATCH_MODE: '-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
   # fixing random connection reset of maven downloads as proposed here: https://github.com/actions/virtual-environments/issues/2715#issuecomment-797388909
   MVN_HTTP_OPTIMIZATION: '-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120'
-  MVN_TEST_COVERAGE: '-Dskip.code.coverage=false'
 
 jobs:
   cache-dependencies:
@@ -40,13 +39,13 @@ jobs:
       - name: Checkout & Prepare
         uses: devonfw-actions/java-maven-setup@main
         with:
-          maven-cache-path: ${{ github.workspace }}/.m2/repository
+          maven-cache-path: ../../.m2/repository
           maven-cache-key: cobigen-dep-${{ hashFiles('**/pom.xml') }}
           clone: false # checkout in a separate / earlier step to allow eager evaluation of parameter expression like workspace or hashFiles
       
       - name: Resolve non-cobigen dependencies
         shell: bash
-        run: mvn -Dmaven.repo.local=${{ github.workspace }}/.m2/repository -pl !com.devonfw.cobigen:com.devonfw.cobigen.eclipse.test org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve-plugins -DexcludeGroupIds=com.devonfw.cobigen -T1C -Pp2-build ${{ env.MVN_BATCH_MODE }} ${{ env.MVN_HTTP_OPTIMIZATION }} || true # never fail
+        run: mvn -Dmaven.repo.local=../../.m2/repository -pl !com.devonfw.cobigen:com.devonfw.cobigen.eclipse.test org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve-plugins -DexcludeGroupIds=com.devonfw.cobigen -T1C -Pp2-build ${{ env.MVN_BATCH_MODE }} ${{ env.MVN_HTTP_OPTIMIZATION }} || true # never fail
 
   build:
     needs: cache-dependencies
@@ -68,7 +67,7 @@ jobs:
       - name: Checkout & Prepare
         uses: devonfw-actions/java-maven-setup@main
         with:
-          maven-cache-path: ${{ github.workspace }}/.m2/repository
+          maven-cache-path: ../../.m2/repository
           maven-cache-key: maven-${{ github.sha }}-${{ matrix.os }}-${{ github.run_number }} # new key will cache
           maven-cache-restore-key: cobigen-dep-${{ hashFiles('**/pom.xml') }}
           java-version: ${{ matrix.javaVersion }}
@@ -117,7 +116,7 @@ jobs:
 
       - uses: devonfw-actions/java-maven-setup@main
         with:
-          maven-cache-path: ${{ github.workspace }}/.m2/repository
+          maven-cache-path: ../../.m2/repository
           maven-cache-key: maven-${{ github.sha }}-${{ matrix.os }}-${{ github.run_number }} # match, restore only
           java-version: ${{ matrix.javaVersion }}
           jacoco-cache-key: jacoco-${{ github.sha }}-${{ matrix.component }} # new key will cache
@@ -125,7 +124,7 @@ jobs:
 
       - name: Test
         shell: bash
-        run: ./build.sh -sdbtc --components ${{ matrix.component }}
+        run: ./build.sh -sdtc --components ${{ matrix.component }}
 
   # Sonar Analysis is done in separate workflow (https://github.com/devonfw/cobigen/blob/master/.github/workflows/sonar-analysis.yml)
   # as of a workaround of potential secret leaking on PRs (https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
@@ -169,7 +168,7 @@ jobs:
 
       - uses: devonfw-actions/java-maven-setup@main
         with:
-          maven-cache-path: ${{ github.workspace }}/.m2/repository
+          maven-cache-path: ../../.m2/repository
           maven-cache-key: cobigen-dep-${{ hashFiles('**/pom.xml') }}
           GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
           GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
