fixing code coverage instrumentation

diff --git a/.github/workflows/maven-build-test.yml b/.github/workflows/maven-build-test.yml
--- a/.github/workflows/maven-build-test.yml
+++ b/.github/workflows/maven-build-test.yml
@@ -18,7 +18,11 @@ on:
       - 'solicitor/**'
       - '**.asciidoc'
 
-# Try fixing random Connection Reset on Maven downloads by '-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120' as proposed here: https://github.com/actions/virtual-environments/issues/2715#issuecomment-797388909
+env:
+  MVN_BATCH_MODE: '-Djansi.force=true -Djansi.passthrough=true -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
+  # fixing random connection reset of maven downloads as proposed here: https://github.com/actions/virtual-environments/issues/2715#issuecomment-797388909
+  MVN_HTTP_OPTIMIZATION: '-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120'
+  MVN_TEST_COVERAGE: '-Dskip.code.coverage=false'
 
 jobs:
   cache-dependencies:
@@ -33,7 +37,7 @@ jobs:
           clone: false
       
       - name: Resolve non-cobigen dependencies
-        run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve -DexcludeGroupIds=com.devonfw.cobigen -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -T1C -P!p2-build -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 || true # never fail
+        run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve -DexcludeGroupIds=com.devonfw.cobigen -T1C -P!p2-build $MVN_BATCH_MODE $MVN_HTTP_OPTIMIZATION || true # never fail
     
   build-and-test-core:
     needs: cache-dependencies
@@ -55,7 +59,7 @@ jobs:
       - name: Build & Test Core
         shell: bash
         run: |
-          mvn install -f cobigen --projects !cobigen-core-systemtest -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
+          mvn install -f cobigen --projects !cobigen-core-systemtest $MVN_BATCH_MODE $MVN_HTTP_OPTIMIZATION $MVN_TEST_COVERAGE
 
   build-and-test-plugins:
     needs: build-and-test-core
@@ -78,7 +82,7 @@ jobs:
       - name: Build & Test Plugins
         shell: bash
         run: |
-          mvn install -f cobigen-plugins -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
+          mvn install -f cobigen-plugins $MVN_BATCH_MODE $MVN_HTTP_OPTIMIZATION $MVN_TEST_COVERAGE
 
   build-plugins-p2:
     needs: build-and-test-plugins
@@ -104,8 +108,8 @@ jobs:
       - name: Build Plugins UpdateSite
         shell: bash
         run: |
-          mvn package -DskipTests -f cobigen-plugins bundle:bundle -Pp2-bundle --projects !cobigen-javaplugin-parent/cobigen-javaplugin-model,!cobigen-openapiplugin-parent/cobigen-openapiplugin-model,!:plugins-parent,!cobigen-javaplugin-parent,!cobigen-openapiplugin-parent,!cobigen-templateengines -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
-          mvn install -DskipTests -f cobigen-plugins bundle:bundle -Pp2-bundle p2:site --projects !cobigen-javaplugin-parent/cobigen-javaplugin-model,!cobigen-openapiplugin-parent/cobigen-openapiplugin-model,!:plugins-parent,!cobigen-javaplugin-parent,!cobigen-openapiplugin-parent,!cobigen-templateengines -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
+          mvn package -DskipTests -f cobigen-plugins bundle:bundle -Pp2-bundle --projects !cobigen-javaplugin-parent/cobigen-javaplugin-model,!cobigen-openapiplugin-parent/cobigen-openapiplugin-model,!:plugins-parent,!cobigen-javaplugin-parent,!cobigen-openapiplugin-parent,!cobigen-templateengines $MVN_BATCH_MODE $MVN_HTTP_OPTIMIZATION
+          mvn install -DskipTests -f cobigen-plugins bundle:bundle -Pp2-bundle p2:site --projects !cobigen-javaplugin-parent/cobigen-javaplugin-model,!cobigen-openapiplugin-parent/cobigen-openapiplugin-model,!:plugins-parent,!cobigen-javaplugin-parent,!cobigen-openapiplugin-parent,!cobigen-templateengines $MVN_BATCH_MODE $MVN_HTTP_OPTIMIZATION
 
   run-core-systemtest:
     needs: build-and-test-plugins
@@ -126,8 +130,7 @@ jobs:
 
       - name: Run Core Systemtest
         shell: bash
-        run: |
-          mvn test -f cobigen/cobigen-core-systemtest -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
+        run: mvn test -f cobigen/cobigen-core-systemtest $MVN_BATCH_MODE $MVN_HTTP_OPTIMIZATION $MVN_TEST_COVERAGE
 
   build-and-test-eclipse-plugin:
     needs: build-plugins-p2
@@ -162,7 +165,7 @@ jobs:
       - name: Build Plugins
         uses: GabrielBB/xvfb-action@v1.5
         with:
-          run: mvn install -f cobigen-eclipse -Pp2-build -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dsurefire.rerunFailingTestsCount=2 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
+          run: mvn install -f cobigen-eclipse -Pp2-build $MVN_BATCH_MODE $MVN_HTTP_OPTIMIZATION $MVN_TEST_COVERAGE
 
   build-and-test-maven-plugin:
     needs: build-and-test-plugins
@@ -184,7 +187,7 @@ jobs:
       - name: Build & Test Maven Plugin
         shell: bash
         run: |
-          mvn install -f cobigen-maven -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
+          mvn install -f cobigen-maven $MVN_BATCH_MODE $MVN_HTTP_OPTIMIZATION $MVN_TEST_COVERAGE
 
   build-and-test-cli:
     needs: build-and-test-templates
@@ -207,7 +210,7 @@ jobs:
       - name: Build & Test CLI
         shell: bash
         run: |
-          mvn install -f cobigen-cli -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
+          mvn install -f cobigen-cli $MVN_BATCH_MODE $MVN_HTTP_OPTIMIZATION $MVN_TEST_COVERAGE
 
   build-and-test-templates:
     needs: build-and-test-maven-plugin
@@ -230,7 +233,7 @@ jobs:
       - name: Build & Test Templates
         shell: bash
         run: |
-          mvn install -f cobigen-templates -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
+          mvn install -f cobigen-templates $MVN_BATCH_MODE $MVN_HTTP_OPTIMIZATION $MVN_TEST_COVERAGE
 
   sonar-analysis:
     needs: [build-and-test-maven-plugin, build-and-test-templates, run-core-systemtest, build-and-test-eclipse-plugin, build-and-test-cli]
@@ -272,7 +275,7 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
           git fetch --unshallow
-          mvn verify sonar:sonar -X -Dsonar.verbose=true -B -DskipTests -Dskip.code.coverage=false -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
+          mvn verify sonar:sonar $MVN_BATCH_MODE $MVN_HTTP_OPTIMIZATION $MVN_TEST_COVERAGE
   
   release:
     needs: [build-and-test-maven-plugin, build-and-test-templates, run-core-systemtest, build-and-test-eclipse-plugin, build-and-test-cli]
